name: Continuous Integration
on:
  push:

jobs:
  commitlint:
    name: CommitLint
    if: github.event.action != 'closed' || github.event.pull_request.merged != true
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install commitlint
        run: |
          bun install conventional-changelog-conventionalcommits
          bun install commitlint@latest
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bunx commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  format:
    name: SwiftFormat
    runs-on: macos-latest 
    if: github.event.action != 'closed' || github.event.pull_request.merged != true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Swift Version
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: 6.1.0
      - name: Swift Version
        run: swift --version
      - name: Format
        run: |
          swiftformat --lint . --reporter github-actions-log
  lint:
    name: SwiftLint
    runs-on: macos-latest 
    if: github.event.action != 'closed' || github.event.pull_request.merged != true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Swift Version
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: 6.1.0
      - name: Swift Version
        run: swift --version
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --reporter github-actions