name: Unit Test 
on:
  - push

jobs:
  build:
    name: Build 
    runs-on: macos-latest 
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: 5.10.1 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test